apiVersion: v1
kind: Secret
metadata:
  name: bloghub-backend-secrets
type: Opaque
stringData:
  DB_URL: "jdbc:mysql://mysql:3306/bloghub_db?useSSL=false&serverTimezone=UTC"
  DB_USERNAME: "bloghub_user"
  DB_PASSWORD: "replace-me"
  JWT_SECRET: "replace-with-base64-64-byte-secret"
  APP_BOOTSTRAP_ADMIN_ENABLED: "false"
  APP_BOOTSTRAP_ADMIN_PASSWORD: ""
